"""
Extract additional features from cro_submissions_raw.jsonl.

Extracts has_fixed_charge and charge_holder_is_bank per company from
cro_submissions_raw.jsonl. Reads entirely from the local JSONL file and
makes no API calls.

Output: data/raw/01_CRO_Raw/cro_charges_extended.csv
    company_num, has_fixed_charge, charge_holder_is_bank

Runtime: ~5-10 minutes (reads 814K JSONL lines, no network calls)

Usage:
    python src/extract_from_raw.py
"""
import json, sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))
from src.config import RAW_FILES

FLOATING_WORDS = {"floating", "debenture", "all assets", "all property"}
FIXED_WORDS    = {"fixed", "specific", "fixed charge"}
BANK_WORDS     = {"bank", "finance", "credit union", "institution", "lender",
                  "ulster bank", "bank of ireland", "aib", "allied irish",
                  "permanent tsb", "kbc", "revolut", "finance ireland",
                  "barclays", "deutsche", "citibank", "hsbc", "santander",
                  "rabobank", "bnp", "nordic", "nordic capital", "lending"}

CHARGE_FORMS    = {"c1", "c1a", "c1b", "c1c", "c2"}
DISCHARGE_FORMS = {"c6", "c7", "c17"}


def is_form(fk, codes):
    for c in [x.lower() for x in codes]:
        if fk == c: return True
        if fk.startswith(c + " ") or fk.startswith(c + "-"): return True
        if "form " + c in fk: return True
        if " " + c + " " in fk: return True
    return False


def parse_charge_extended(company_num, subs):
    """Extract has_fixed_charge and charge_holder_is_bank from raw submissions."""
    if not isinstance(subs, list):
        return {"company_num": company_num, "has_fixed_charge": 0, "charge_holder_is_bank": 0}

    has_fixed = 0
    holder_is_bank = 0

    for sub in subs:
        fk = str(sub.get("sub_type_desc") or "").lower().strip()
        is_charge = is_form(fk, CHARGE_FORMS) or "particulars of a charge" in fk
        is_discharge = is_form(fk, DISCHARGE_FORMS) or "satisfaction" in fk

        if is_charge and not is_discharge:
            if any(w in fk for w in FIXED_WORDS) and not any(w in fk for w in FLOATING_WORDS):
                has_fixed = 1
            if not any(w in fk for w in FLOATING_WORDS) and "debenture" not in fk:
                desc = str(sub.get("description") or "").lower()
                if any(w in desc for w in FIXED_WORDS):
                    has_fixed = 1
                elif not any(w in desc for w in FLOATING_WORDS):
                    has_fixed = 1  # Default: fixed charge

            holder = str(
                sub.get("chargee") or sub.get("charge_holder") or
                sub.get("lender_name") or sub.get("secured_party") or ""
            ).lower()
            if any(w in holder for w in BANK_WORDS):
                holder_is_bank = 1

    return {"company_num": company_num, "has_fixed_charge": has_fixed,
            "charge_holder_is_bank": holder_is_bank}


def main():
    jsonl_path = RAW_FILES.get("cro_raw_jsonl")
    if not jsonl_path or not Path(jsonl_path).exists():
        print(f"ERROR: cro_submissions_raw.jsonl not found at {jsonl_path}")
        print("  This file is generated by: python src/01_collect_cro_submissions_all.py")
        return

    out_path = Path(jsonl_path).parent / "cro_charges_extended.csv"
    print("=" * 60)
    print("extract_from_raw.py: Fixed Charge & Bank Holder Features")
    print("=" * 60)
    print(f"  Input : {jsonl_path}")
    print(f"  Output: {out_path}")
    print(f"  No API calls: reads entirely from local JSONL\n")

    results = []
    n_total = 0
    n_fixed = 0
    n_bank  = 0

    with open(jsonl_path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                company_num = rec.get("company_num", "")
                subs = rec.get("submissions", [])
                row = parse_charge_extended(company_num, subs)
                results.append(row)
                n_total += 1
                n_fixed += row["has_fixed_charge"]
                n_bank  += row["charge_holder_is_bank"]

                if (i + 1) % 100_000 == 0:
                    print(f"  Processed {i+1:,}  has_fixed={n_fixed:,}  holder_is_bank={n_bank:,}")
            except Exception:
                continue

    import pandas as pd
    df = pd.DataFrame(results)
    df.to_csv(out_path, index=False)

    print(f"\nComplete: {n_total:,} companies")
    print(f"  has_fixed_charge       : {n_fixed:,} ({n_fixed/max(n_total,1):.1%})")
    print(f"  charge_holder_is_bank  : {n_bank:,}  ({n_bank/max(n_total,1):.1%})")
    print(f"  Saved: {out_path}")


if __name__ == "__main__":
    main()
